// @flow strict
import type { VehicleType, Image, DimensionsInput,DocumentData, VehicleCategory } from '../__graphql__/graphql';

declare type AddVehicleForm = {|
  __id: "client:local:addVehicleForm",
  __typename: "AddVehicleForm",
  model: string,
  category: Array<VehicleCategory>,
  year: number,
  plateNumber: string,
  isOwn: boolean,
  odometer: string,
  color: string,
  pax: string,
  fuelType: string,
  transmission: string,
  baseKmDay: string,
  extraKmPrice: string,
  price: string,
  fuel: string,
  odometer: string,
  franchise: string,
  deposit: string,
  partner: ?Partner,
  photos: Array<Photo>,
  documents: Array<DocumentData>,
  damages: Array<Damage>,
  insurance: Array<Insurance>,
  brand: ?Brand,
  base: ?Address,
  tariffs: Array<VehicleTariff>,
  excludeFromCalculator: boolean,
  deleted?: boolean,
  hideFromBooking?: boolean,
  complectations: Array<string>,
  type: VehicleType,
  damagesImages: Array<Image>,
  licenceType: string,
  loadDimensions: DimensionsInput,
  loadCapacity: number,
  franchisePercents: number,
  franchiseTheft: number,
  franchiseDamage: number,
  franchiseCasco: number,
  offices: Array<Office>,
  unlimitedKilometers: boolean,
|};
