// flow-typed signature: 1b8ec6865ebceb852835c056dc7aaa72
// flow-typed version: <<STUB>>/@formatjs/intl-pluralrules_v1.5.1/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@formatjs/intl-pluralrules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@formatjs/intl-pluralrules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@formatjs/intl-pluralrules/dist-es6/core' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/dist-es6' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/dist-es6/polyfill-locales' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/dist-es6/polyfill' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/dist/core' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/dist' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/af' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ak' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/am' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ar' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/as' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/asa' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ast' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/az' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/be' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/bem' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/bez' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/bg' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/bm' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/bn' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/bo' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/br' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/brx' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/bs' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ca' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ce' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ceb' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/cgg' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/chr' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ckb' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/cs' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/cy' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/da' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/de' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/dsb' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/dz' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ee' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/el' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/en' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/eo' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/es' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/et' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/eu' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/fa' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ff' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/fi' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/fil' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/fo' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/fr' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/fur' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/fy' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ga' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/gd' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/gl' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/gsw' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/gu' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/gv' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ha' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/haw' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/he' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/hi' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/hr' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/hsb' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/hu' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/hy' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ia' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/id' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ig' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ii' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/is' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/it' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ja' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/jgo' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/jmc' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/jv' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ka' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/kab' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/kde' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/kea' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/kk' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/kkj' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/kl' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/km' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/kn' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ko' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ks' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ksb' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ksh' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ku' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/kw' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ky' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/lag' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/lb' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/lg' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/lkt' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ln' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/lo' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/lt' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/lv' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/mas' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/mg' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/mgo' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/mk' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ml' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/mn' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/mr' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ms' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/mt' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/my' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/naq' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/nb' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/nd' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ne' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/nl' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/nn' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/nnh' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/nyn' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/om' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/or' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/os' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/pa' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/pl' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/prg' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ps' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/pt' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/rm' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ro' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/rof' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/root' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ru' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/rwk' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/sah' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/saq' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/sd' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/se' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/seh' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ses' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/sg' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/shi' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/si' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/sk' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/sl' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/smn' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/sn' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/so' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/sq' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/sr' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/sv' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/sw' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ta' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/te' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/teo' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/th' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ti' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/tk' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/to' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/tr' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/tzm' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ug' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/uk' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/ur' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/uz' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/vi' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/vo' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/vun' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/wae' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/wo' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/xh' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/xog' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/yi' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/yo' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/yue' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/zh' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/locale-data/zu' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/dist/polyfill-with-locales-for-test262.min' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/dist/polyfill' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/dist/umd/intl-pluralrules' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/dist/umd/intl-pluralrules.min' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/dist/umd/polyfill-with-locales' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/dist/umd/polyfill' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/lib/core' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/lib' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/lib/polyfill' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/polyfill-locales' {
  declare module.exports: any;
}

declare module '@formatjs/intl-pluralrules/polyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module '@formatjs/intl-pluralrules/dist-es6/core.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/dist-es6/core'>;
}
declare module '@formatjs/intl-pluralrules/dist-es6/index' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/dist-es6'>;
}
declare module '@formatjs/intl-pluralrules/dist-es6/index.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/dist-es6'>;
}
declare module '@formatjs/intl-pluralrules/dist-es6/polyfill-locales.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/dist-es6/polyfill-locales'>;
}
declare module '@formatjs/intl-pluralrules/dist-es6/polyfill.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/dist-es6/polyfill'>;
}
declare module '@formatjs/intl-pluralrules/dist/core.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/dist/core'>;
}
declare module '@formatjs/intl-pluralrules/dist/index' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/dist'>;
}
declare module '@formatjs/intl-pluralrules/dist/index.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/dist'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/af.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/af'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ak.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ak'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/am.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/am'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ar.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ar'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/as.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/as'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/asa.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/asa'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ast.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ast'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/az.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/az'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/be.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/be'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/bem.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/bem'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/bez.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/bez'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/bg.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/bg'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/bm.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/bm'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/bn.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/bn'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/bo.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/bo'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/br.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/br'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/brx.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/brx'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/bs.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/bs'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ca.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ca'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ce.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ce'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ceb.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ceb'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/cgg.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/cgg'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/chr.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/chr'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ckb.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ckb'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/cs.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/cs'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/cy.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/cy'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/da.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/da'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/de.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/de'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/dsb.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/dsb'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/dz.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/dz'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ee.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ee'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/el.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/el'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/en.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/en'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/eo.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/eo'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/es.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/es'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/et.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/et'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/eu.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/eu'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/fa.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/fa'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ff.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ff'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/fi.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/fi'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/fil.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/fil'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/fo.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/fo'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/fr.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/fr'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/fur.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/fur'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/fy.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/fy'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ga.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ga'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/gd.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/gd'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/gl.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/gl'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/gsw.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/gsw'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/gu.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/gu'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/gv.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/gv'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ha.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ha'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/haw.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/haw'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/he.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/he'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/hi.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/hi'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/hr.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/hr'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/hsb.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/hsb'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/hu.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/hu'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/hy.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/hy'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ia.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ia'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/id.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/id'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ig.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ig'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ii.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ii'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/is.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/is'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/it.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/it'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ja.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ja'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/jgo.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/jgo'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/jmc.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/jmc'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/jv.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/jv'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ka.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ka'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/kab.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/kab'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/kde.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/kde'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/kea.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/kea'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/kk.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/kk'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/kkj.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/kkj'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/kl.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/kl'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/km.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/km'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/kn.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/kn'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ko.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ko'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ks.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ks'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ksb.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ksb'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ksh.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ksh'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ku.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ku'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/kw.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/kw'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ky.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ky'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/lag.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/lag'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/lb.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/lb'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/lg.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/lg'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/lkt.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/lkt'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ln.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ln'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/lo.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/lo'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/lt.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/lt'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/lv.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/lv'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/mas.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/mas'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/mg.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/mg'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/mgo.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/mgo'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/mk.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/mk'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ml.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ml'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/mn.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/mn'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/mr.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/mr'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ms.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ms'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/mt.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/mt'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/my.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/my'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/naq.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/naq'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/nb.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/nb'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/nd.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/nd'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ne.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ne'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/nl.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/nl'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/nn.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/nn'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/nnh.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/nnh'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/nyn.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/nyn'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/om.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/om'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/or.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/or'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/os.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/os'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/pa.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/pa'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/pl.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/pl'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/prg.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/prg'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ps.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ps'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/pt.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/pt'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/rm.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/rm'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ro.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ro'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/rof.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/rof'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/root.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/root'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ru.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ru'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/rwk.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/rwk'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/sah.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/sah'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/saq.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/saq'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/sd.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/sd'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/se.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/se'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/seh.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/seh'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ses.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ses'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/sg.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/sg'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/shi.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/shi'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/si.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/si'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/sk.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/sk'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/sl.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/sl'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/smn.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/smn'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/sn.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/sn'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/so.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/so'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/sq.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/sq'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/sr.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/sr'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/sv.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/sv'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/sw.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/sw'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ta.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ta'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/te.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/te'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/teo.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/teo'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/th.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/th'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ti.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ti'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/tk.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/tk'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/to.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/to'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/tr.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/tr'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/tzm.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/tzm'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ug.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ug'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/uk.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/uk'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/ur.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/ur'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/uz.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/uz'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/vi.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/vi'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/vo.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/vo'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/vun.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/vun'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/wae.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/wae'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/wo.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/wo'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/xh.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/xh'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/xog.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/xog'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/yi.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/yi'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/yo.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/yo'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/yue.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/yue'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/zh.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/zh'>;
}
declare module '@formatjs/intl-pluralrules/locale-data/zu.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/locale-data/zu'>;
}
declare module '@formatjs/intl-pluralrules/dist/polyfill-with-locales-for-test262.min.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/dist/polyfill-with-locales-for-test262.min'>;
}
declare module '@formatjs/intl-pluralrules/dist/polyfill.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/dist/polyfill'>;
}
declare module '@formatjs/intl-pluralrules/dist/umd/intl-pluralrules.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/dist/umd/intl-pluralrules'>;
}
declare module '@formatjs/intl-pluralrules/dist/umd/intl-pluralrules.min.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/dist/umd/intl-pluralrules.min'>;
}
declare module '@formatjs/intl-pluralrules/dist/umd/polyfill-with-locales.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/dist/umd/polyfill-with-locales'>;
}
declare module '@formatjs/intl-pluralrules/dist/umd/polyfill.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/dist/umd/polyfill'>;
}
declare module '@formatjs/intl-pluralrules/lib/core.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/lib/core'>;
}
declare module '@formatjs/intl-pluralrules/lib/index' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/lib'>;
}
declare module '@formatjs/intl-pluralrules/lib/index.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/lib'>;
}
declare module '@formatjs/intl-pluralrules/lib/polyfill.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/lib/polyfill'>;
}
declare module '@formatjs/intl-pluralrules/polyfill-locales.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/polyfill-locales'>;
}
declare module '@formatjs/intl-pluralrules/polyfill.js' {
  declare module.exports: $Exports<'@formatjs/intl-pluralrules/polyfill'>;
}
