// flow-typed signature: ee9804eac18c57ee3a2b54e9cb9f73b0
// flow-typed version: <<STUB>>/block-timer_v0.1.1/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'block-timer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'block-timer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'block-timer/index' {
  declare module.exports: $Exports<'block-timer'>;
}
declare module 'block-timer/index.js' {
  declare module.exports: $Exports<'block-timer'>;
}
