// flow-typed signature: 76b2f731519cf10a7532d2ab2212211b
// flow-typed version: <<STUB>>/cloudinary_v1.32.0/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cloudinary'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cloudinary' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cloudinary/babel.config' {
  declare module.exports: any;
}

declare module 'cloudinary/cloudinary' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/api_client/call_account_api' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/api_client/call_api' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/api_client/execute_request' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/api' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/auth_token' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/cache' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/cache/FileKeyValueStorage' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/cache/KeyValueCacheAdapter' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/cloudinary' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/config' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/preloaded_file' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/provisioning/account' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/upload_stream' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/uploader' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/utils/consts' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/utils/crc32' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/utils/encoding/base64Encode' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/utils/encoding/base64EncodeURL' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/utils/encoding/encodeDoubleArray' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/utils/encoding/sdkAnalytics/getSDKVersions' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/utils/encoding/smart_escape' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/utils/ensureOption' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/utils/ensurePresenceOf' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/utils/entries' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/utils/generateBreakpoints' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/utils' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/utils/isRemoteUrl' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/utils/parsing/consumeOption' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/utils/parsing/toArray' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/utils/rimraf' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/utils/srcsetUtils' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/utils/utf8_encode' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/v2/api' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/v2' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/v2/search' {
  declare module.exports: any;
}

declare module 'cloudinary/lib-es5/v2/uploader' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/api_client/call_account_api' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/api_client/call_api' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/api_client/execute_request' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/api' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/auth_token' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/cache' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/cache/FileKeyValueStorage' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/cache/KeyValueCacheAdapter' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/cloudinary' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/config' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/preloaded_file' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/provisioning/account' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/upload_stream' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/uploader' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/utils/consts' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/utils/crc32' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/utils/encoding/base64Encode' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/utils/encoding/base64EncodeURL' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/utils/encoding/encodeDoubleArray' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/utils/encoding/sdkAnalytics/getSDKVersions' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/utils/encoding/smart_escape' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/utils/ensureOption' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/utils/ensurePresenceOf' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/utils/entries' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/utils/generateBreakpoints' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/utils' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/utils/isRemoteUrl' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/utils/parsing/consumeOption' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/utils/parsing/toArray' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/utils/rimraf' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/utils/srcsetUtils' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/utils/utf8_encode' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/v2/api' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/v2' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/v2/search' {
  declare module.exports: any;
}

declare module 'cloudinary/lib/v2/uploader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cloudinary/babel.config.js' {
  declare module.exports: $Exports<'cloudinary/babel.config'>;
}
declare module 'cloudinary/cloudinary.js' {
  declare module.exports: $Exports<'cloudinary/cloudinary'>;
}
declare module 'cloudinary/lib-es5/api_client/call_account_api.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/api_client/call_account_api'>;
}
declare module 'cloudinary/lib-es5/api_client/call_api.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/api_client/call_api'>;
}
declare module 'cloudinary/lib-es5/api_client/execute_request.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/api_client/execute_request'>;
}
declare module 'cloudinary/lib-es5/api.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/api'>;
}
declare module 'cloudinary/lib-es5/auth_token.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/auth_token'>;
}
declare module 'cloudinary/lib-es5/cache.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/cache'>;
}
declare module 'cloudinary/lib-es5/cache/FileKeyValueStorage.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/cache/FileKeyValueStorage'>;
}
declare module 'cloudinary/lib-es5/cache/KeyValueCacheAdapter.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/cache/KeyValueCacheAdapter'>;
}
declare module 'cloudinary/lib-es5/cloudinary.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/cloudinary'>;
}
declare module 'cloudinary/lib-es5/config.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/config'>;
}
declare module 'cloudinary/lib-es5/preloaded_file.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/preloaded_file'>;
}
declare module 'cloudinary/lib-es5/provisioning/account.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/provisioning/account'>;
}
declare module 'cloudinary/lib-es5/upload_stream.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/upload_stream'>;
}
declare module 'cloudinary/lib-es5/uploader.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/uploader'>;
}
declare module 'cloudinary/lib-es5/utils/consts.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/utils/consts'>;
}
declare module 'cloudinary/lib-es5/utils/crc32.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/utils/crc32'>;
}
declare module 'cloudinary/lib-es5/utils/encoding/base64Encode.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/utils/encoding/base64Encode'>;
}
declare module 'cloudinary/lib-es5/utils/encoding/base64EncodeURL.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/utils/encoding/base64EncodeURL'>;
}
declare module 'cloudinary/lib-es5/utils/encoding/encodeDoubleArray.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/utils/encoding/encodeDoubleArray'>;
}
declare module 'cloudinary/lib-es5/utils/encoding/sdkAnalytics/getSDKVersions.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/utils/encoding/sdkAnalytics/getSDKVersions'>;
}
declare module 'cloudinary/lib-es5/utils/encoding/smart_escape.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/utils/encoding/smart_escape'>;
}
declare module 'cloudinary/lib-es5/utils/ensureOption.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/utils/ensureOption'>;
}
declare module 'cloudinary/lib-es5/utils/ensurePresenceOf.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/utils/ensurePresenceOf'>;
}
declare module 'cloudinary/lib-es5/utils/entries.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/utils/entries'>;
}
declare module 'cloudinary/lib-es5/utils/generateBreakpoints.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/utils/generateBreakpoints'>;
}
declare module 'cloudinary/lib-es5/utils/index' {
  declare module.exports: $Exports<'cloudinary/lib-es5/utils'>;
}
declare module 'cloudinary/lib-es5/utils/index.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/utils'>;
}
declare module 'cloudinary/lib-es5/utils/isRemoteUrl.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/utils/isRemoteUrl'>;
}
declare module 'cloudinary/lib-es5/utils/parsing/consumeOption.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/utils/parsing/consumeOption'>;
}
declare module 'cloudinary/lib-es5/utils/parsing/toArray.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/utils/parsing/toArray'>;
}
declare module 'cloudinary/lib-es5/utils/rimraf.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/utils/rimraf'>;
}
declare module 'cloudinary/lib-es5/utils/srcsetUtils.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/utils/srcsetUtils'>;
}
declare module 'cloudinary/lib-es5/utils/utf8_encode.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/utils/utf8_encode'>;
}
declare module 'cloudinary/lib-es5/v2/api.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/v2/api'>;
}
declare module 'cloudinary/lib-es5/v2/index' {
  declare module.exports: $Exports<'cloudinary/lib-es5/v2'>;
}
declare module 'cloudinary/lib-es5/v2/index.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/v2'>;
}
declare module 'cloudinary/lib-es5/v2/search.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/v2/search'>;
}
declare module 'cloudinary/lib-es5/v2/uploader.js' {
  declare module.exports: $Exports<'cloudinary/lib-es5/v2/uploader'>;
}
declare module 'cloudinary/lib/api_client/call_account_api.js' {
  declare module.exports: $Exports<'cloudinary/lib/api_client/call_account_api'>;
}
declare module 'cloudinary/lib/api_client/call_api.js' {
  declare module.exports: $Exports<'cloudinary/lib/api_client/call_api'>;
}
declare module 'cloudinary/lib/api_client/execute_request.js' {
  declare module.exports: $Exports<'cloudinary/lib/api_client/execute_request'>;
}
declare module 'cloudinary/lib/api.js' {
  declare module.exports: $Exports<'cloudinary/lib/api'>;
}
declare module 'cloudinary/lib/auth_token.js' {
  declare module.exports: $Exports<'cloudinary/lib/auth_token'>;
}
declare module 'cloudinary/lib/cache.js' {
  declare module.exports: $Exports<'cloudinary/lib/cache'>;
}
declare module 'cloudinary/lib/cache/FileKeyValueStorage.js' {
  declare module.exports: $Exports<'cloudinary/lib/cache/FileKeyValueStorage'>;
}
declare module 'cloudinary/lib/cache/KeyValueCacheAdapter.js' {
  declare module.exports: $Exports<'cloudinary/lib/cache/KeyValueCacheAdapter'>;
}
declare module 'cloudinary/lib/cloudinary.js' {
  declare module.exports: $Exports<'cloudinary/lib/cloudinary'>;
}
declare module 'cloudinary/lib/config.js' {
  declare module.exports: $Exports<'cloudinary/lib/config'>;
}
declare module 'cloudinary/lib/preloaded_file.js' {
  declare module.exports: $Exports<'cloudinary/lib/preloaded_file'>;
}
declare module 'cloudinary/lib/provisioning/account.js' {
  declare module.exports: $Exports<'cloudinary/lib/provisioning/account'>;
}
declare module 'cloudinary/lib/upload_stream.js' {
  declare module.exports: $Exports<'cloudinary/lib/upload_stream'>;
}
declare module 'cloudinary/lib/uploader.js' {
  declare module.exports: $Exports<'cloudinary/lib/uploader'>;
}
declare module 'cloudinary/lib/utils/consts.js' {
  declare module.exports: $Exports<'cloudinary/lib/utils/consts'>;
}
declare module 'cloudinary/lib/utils/crc32.js' {
  declare module.exports: $Exports<'cloudinary/lib/utils/crc32'>;
}
declare module 'cloudinary/lib/utils/encoding/base64Encode.js' {
  declare module.exports: $Exports<'cloudinary/lib/utils/encoding/base64Encode'>;
}
declare module 'cloudinary/lib/utils/encoding/base64EncodeURL.js' {
  declare module.exports: $Exports<'cloudinary/lib/utils/encoding/base64EncodeURL'>;
}
declare module 'cloudinary/lib/utils/encoding/encodeDoubleArray.js' {
  declare module.exports: $Exports<'cloudinary/lib/utils/encoding/encodeDoubleArray'>;
}
declare module 'cloudinary/lib/utils/encoding/sdkAnalytics/getSDKVersions.js' {
  declare module.exports: $Exports<'cloudinary/lib/utils/encoding/sdkAnalytics/getSDKVersions'>;
}
declare module 'cloudinary/lib/utils/encoding/smart_escape.js' {
  declare module.exports: $Exports<'cloudinary/lib/utils/encoding/smart_escape'>;
}
declare module 'cloudinary/lib/utils/ensureOption.js' {
  declare module.exports: $Exports<'cloudinary/lib/utils/ensureOption'>;
}
declare module 'cloudinary/lib/utils/ensurePresenceOf.js' {
  declare module.exports: $Exports<'cloudinary/lib/utils/ensurePresenceOf'>;
}
declare module 'cloudinary/lib/utils/entries.js' {
  declare module.exports: $Exports<'cloudinary/lib/utils/entries'>;
}
declare module 'cloudinary/lib/utils/generateBreakpoints.js' {
  declare module.exports: $Exports<'cloudinary/lib/utils/generateBreakpoints'>;
}
declare module 'cloudinary/lib/utils/index' {
  declare module.exports: $Exports<'cloudinary/lib/utils'>;
}
declare module 'cloudinary/lib/utils/index.js' {
  declare module.exports: $Exports<'cloudinary/lib/utils'>;
}
declare module 'cloudinary/lib/utils/isRemoteUrl.js' {
  declare module.exports: $Exports<'cloudinary/lib/utils/isRemoteUrl'>;
}
declare module 'cloudinary/lib/utils/parsing/consumeOption.js' {
  declare module.exports: $Exports<'cloudinary/lib/utils/parsing/consumeOption'>;
}
declare module 'cloudinary/lib/utils/parsing/toArray.js' {
  declare module.exports: $Exports<'cloudinary/lib/utils/parsing/toArray'>;
}
declare module 'cloudinary/lib/utils/rimraf.js' {
  declare module.exports: $Exports<'cloudinary/lib/utils/rimraf'>;
}
declare module 'cloudinary/lib/utils/srcsetUtils.js' {
  declare module.exports: $Exports<'cloudinary/lib/utils/srcsetUtils'>;
}
declare module 'cloudinary/lib/utils/utf8_encode.js' {
  declare module.exports: $Exports<'cloudinary/lib/utils/utf8_encode'>;
}
declare module 'cloudinary/lib/v2/api.js' {
  declare module.exports: $Exports<'cloudinary/lib/v2/api'>;
}
declare module 'cloudinary/lib/v2/index' {
  declare module.exports: $Exports<'cloudinary/lib/v2'>;
}
declare module 'cloudinary/lib/v2/index.js' {
  declare module.exports: $Exports<'cloudinary/lib/v2'>;
}
declare module 'cloudinary/lib/v2/search.js' {
  declare module.exports: $Exports<'cloudinary/lib/v2/search'>;
}
declare module 'cloudinary/lib/v2/uploader.js' {
  declare module.exports: $Exports<'cloudinary/lib/v2/uploader'>;
}
