// flow-typed signature: f493725558d57ce9446f264954f0e4e5
// flow-typed version: <<STUB>>/country-to-iso_v1.3.0/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'country-to-iso'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'country-to-iso' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'country-to-iso/jest.config' {
  declare module.exports: any;
}

declare module 'country-to-iso/lib/cjs/country-to-code' {
  declare module.exports: any;
}

declare module 'country-to-iso/lib/cjs' {
  declare module.exports: any;
}

declare module 'country-to-iso/lib/cjs/scripts/generate' {
  declare module.exports: any;
}

declare module 'country-to-iso/lib/cjs/scripts/seed' {
  declare module.exports: any;
}

declare module 'country-to-iso/lib/cjs/utils/latinize' {
  declare module.exports: any;
}

declare module 'country-to-iso/lib/cjs/utils/normalize' {
  declare module.exports: any;
}

declare module 'country-to-iso/lib/cjs/utils/strings' {
  declare module.exports: any;
}

declare module 'country-to-iso/lib/esm/country-to-code' {
  declare module.exports: any;
}

declare module 'country-to-iso/lib/esm' {
  declare module.exports: any;
}

declare module 'country-to-iso/lib/esm/scripts/generate' {
  declare module.exports: any;
}

declare module 'country-to-iso/lib/esm/scripts/seed' {
  declare module.exports: any;
}

declare module 'country-to-iso/lib/esm/utils/latinize' {
  declare module.exports: any;
}

declare module 'country-to-iso/lib/esm/utils/normalize' {
  declare module.exports: any;
}

declare module 'country-to-iso/lib/esm/utils/strings' {
  declare module.exports: any;
}

declare module 'country-to-iso/replace-in-file.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'country-to-iso/jest.config.js' {
  declare module.exports: $Exports<'country-to-iso/jest.config'>;
}
declare module 'country-to-iso/lib/cjs/country-to-code.js' {
  declare module.exports: $Exports<'country-to-iso/lib/cjs/country-to-code'>;
}
declare module 'country-to-iso/lib/cjs/index' {
  declare module.exports: $Exports<'country-to-iso/lib/cjs'>;
}
declare module 'country-to-iso/lib/cjs/index.js' {
  declare module.exports: $Exports<'country-to-iso/lib/cjs'>;
}
declare module 'country-to-iso/lib/cjs/scripts/generate.js' {
  declare module.exports: $Exports<'country-to-iso/lib/cjs/scripts/generate'>;
}
declare module 'country-to-iso/lib/cjs/scripts/seed.js' {
  declare module.exports: $Exports<'country-to-iso/lib/cjs/scripts/seed'>;
}
declare module 'country-to-iso/lib/cjs/utils/latinize.js' {
  declare module.exports: $Exports<'country-to-iso/lib/cjs/utils/latinize'>;
}
declare module 'country-to-iso/lib/cjs/utils/normalize.js' {
  declare module.exports: $Exports<'country-to-iso/lib/cjs/utils/normalize'>;
}
declare module 'country-to-iso/lib/cjs/utils/strings.js' {
  declare module.exports: $Exports<'country-to-iso/lib/cjs/utils/strings'>;
}
declare module 'country-to-iso/lib/esm/country-to-code.js' {
  declare module.exports: $Exports<'country-to-iso/lib/esm/country-to-code'>;
}
declare module 'country-to-iso/lib/esm/index' {
  declare module.exports: $Exports<'country-to-iso/lib/esm'>;
}
declare module 'country-to-iso/lib/esm/index.js' {
  declare module.exports: $Exports<'country-to-iso/lib/esm'>;
}
declare module 'country-to-iso/lib/esm/scripts/generate.js' {
  declare module.exports: $Exports<'country-to-iso/lib/esm/scripts/generate'>;
}
declare module 'country-to-iso/lib/esm/scripts/seed.js' {
  declare module.exports: $Exports<'country-to-iso/lib/esm/scripts/seed'>;
}
declare module 'country-to-iso/lib/esm/utils/latinize.js' {
  declare module.exports: $Exports<'country-to-iso/lib/esm/utils/latinize'>;
}
declare module 'country-to-iso/lib/esm/utils/normalize.js' {
  declare module.exports: $Exports<'country-to-iso/lib/esm/utils/normalize'>;
}
declare module 'country-to-iso/lib/esm/utils/strings.js' {
  declare module.exports: $Exports<'country-to-iso/lib/esm/utils/strings'>;
}
declare module 'country-to-iso/replace-in-file.config.js' {
  declare module.exports: $Exports<'country-to-iso/replace-in-file.config'>;
}
