// flow-typed signature: 0dab25b7c8af914abb6d2207544b012d
// flow-typed version: <<STUB>>/express-graphql_v0.9.0/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-graphql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-graphql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-graphql/parseBody' {
  declare module.exports: any;
}

declare module 'express-graphql/renderGraphiQL' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-graphql/index' {
  declare module.exports: $Exports<'express-graphql'>;
}
declare module 'express-graphql/index.js' {
  declare module.exports: $Exports<'express-graphql'>;
}
declare module 'express-graphql/parseBody.js' {
  declare module.exports: $Exports<'express-graphql/parseBody'>;
}
declare module 'express-graphql/renderGraphiQL.js' {
  declare module.exports: $Exports<'express-graphql/renderGraphiQL'>;
}
