// flow-typed signature: 3d5dcd1954232da529003f585d71610c
// flow-typed version: <<STUB>>/fauna_v0.7.2/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fauna'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fauna' {
  declare export type Options = {
    arguments?: { [key: string]: string | number | boolean | null; },
    ...
  };

  declare export function fql(...args: (mixed)[]): string;

  declare export class Client {
    constructor(options: { secret: string; }): this;
    query<T>(query: string, options?: Options): Promise<{ data: T; }>;
    close(): void;
  }
}
