// flow-typed signature: 761ca3c8ee6ca56b185abf275f9a2069
// flow-typed version: <<STUB>>/firebase-admin_v8.7.0/flow_v0.111.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebase-admin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebase-admin' {
  declare module.exports: any;
}
