// flow-typed signature: ee711348659c0b6c07a5621e75510bfa
// flow-typed version: <<STUB>>/formidable_v2.1.1/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'formidable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'formidable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'formidable/src/Formidable' {
  declare module.exports: any;
}

declare module 'formidable/src/FormidableError' {
  declare module.exports: any;
}

declare module 'formidable/src' {
  declare module.exports: any;
}

declare module 'formidable/src/parsers/Dummy' {
  declare module.exports: any;
}

declare module 'formidable/src/parsers' {
  declare module.exports: any;
}

declare module 'formidable/src/parsers/JSON' {
  declare module.exports: any;
}

declare module 'formidable/src/parsers/Multipart' {
  declare module.exports: any;
}

declare module 'formidable/src/parsers/OctetStream' {
  declare module.exports: any;
}

declare module 'formidable/src/parsers/Querystring' {
  declare module.exports: any;
}

declare module 'formidable/src/parsers/StreamingQuerystring' {
  declare module.exports: any;
}

declare module 'formidable/src/PersistentFile' {
  declare module.exports: any;
}

declare module 'formidable/src/plugins' {
  declare module.exports: any;
}

declare module 'formidable/src/plugins/json' {
  declare module.exports: any;
}

declare module 'formidable/src/plugins/multipart' {
  declare module.exports: any;
}

declare module 'formidable/src/plugins/octetstream' {
  declare module.exports: any;
}

declare module 'formidable/src/plugins/querystring' {
  declare module.exports: any;
}

declare module 'formidable/src/VolatileFile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'formidable/src/Formidable.js' {
  declare module.exports: $Exports<'formidable/src/Formidable'>;
}
declare module 'formidable/src/FormidableError.js' {
  declare module.exports: $Exports<'formidable/src/FormidableError'>;
}
declare module 'formidable/src/index' {
  declare module.exports: $Exports<'formidable/src'>;
}
declare module 'formidable/src/index.js' {
  declare module.exports: $Exports<'formidable/src'>;
}
declare module 'formidable/src/parsers/Dummy.js' {
  declare module.exports: $Exports<'formidable/src/parsers/Dummy'>;
}
declare module 'formidable/src/parsers/index' {
  declare module.exports: $Exports<'formidable/src/parsers'>;
}
declare module 'formidable/src/parsers/index.js' {
  declare module.exports: $Exports<'formidable/src/parsers'>;
}
declare module 'formidable/src/parsers/JSON.js' {
  declare module.exports: $Exports<'formidable/src/parsers/JSON'>;
}
declare module 'formidable/src/parsers/Multipart.js' {
  declare module.exports: $Exports<'formidable/src/parsers/Multipart'>;
}
declare module 'formidable/src/parsers/OctetStream.js' {
  declare module.exports: $Exports<'formidable/src/parsers/OctetStream'>;
}
declare module 'formidable/src/parsers/Querystring.js' {
  declare module.exports: $Exports<'formidable/src/parsers/Querystring'>;
}
declare module 'formidable/src/parsers/StreamingQuerystring.js' {
  declare module.exports: $Exports<'formidable/src/parsers/StreamingQuerystring'>;
}
declare module 'formidable/src/PersistentFile.js' {
  declare module.exports: $Exports<'formidable/src/PersistentFile'>;
}
declare module 'formidable/src/plugins/index' {
  declare module.exports: $Exports<'formidable/src/plugins'>;
}
declare module 'formidable/src/plugins/index.js' {
  declare module.exports: $Exports<'formidable/src/plugins'>;
}
declare module 'formidable/src/plugins/json.js' {
  declare module.exports: $Exports<'formidable/src/plugins/json'>;
}
declare module 'formidable/src/plugins/multipart.js' {
  declare module.exports: $Exports<'formidable/src/plugins/multipart'>;
}
declare module 'formidable/src/plugins/octetstream.js' {
  declare module.exports: $Exports<'formidable/src/plugins/octetstream'>;
}
declare module 'formidable/src/plugins/querystring.js' {
  declare module.exports: $Exports<'formidable/src/plugins/querystring'>;
}
declare module 'formidable/src/VolatileFile.js' {
  declare module.exports: $Exports<'formidable/src/VolatileFile'>;
}
