// flow-typed signature: 57addc6365392fead1a14485702c4247
// flow-typed version: <<STUB>>/graphql-tools_v9.0.0/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-tools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-tools/cjs' {
  declare module.exports: any;
}

declare module 'graphql-tools/esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-tools/cjs/index' {
  declare module.exports: $Exports<'graphql-tools/cjs'>;
}
declare module 'graphql-tools/cjs/index.js' {
  declare module.exports: $Exports<'graphql-tools/cjs'>;
}
declare module 'graphql-tools/esm/index' {
  declare module.exports: $Exports<'graphql-tools/esm'>;
}
declare module 'graphql-tools/esm/index.js' {
  declare module.exports: $Exports<'graphql-tools/esm'>;
}
