// flow-typed signature: c937a4bc24e5b56eeaeb02071d3b9813
// flow-typed version: <<STUB>>/lodash.merge_v4.6.2/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.merge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.merge' {
  import type { merge } from 'lodash';
  declare module.exports: merge;
}
