// flow-typed signature: fb4c90cf1c693bca343a50739dd5aeef
// flow-typed version: <<STUB>>/material-ui-popup-state_v1.5.1/flow_v0.114.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui-popup-state'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui-popup-state' {
  declare module.exports: any;
}
