// flow-typed signature: 23022ff63435b4ccad58c9355ae20daf
// flow-typed version: <<STUB>>/moesif-express_v2.9.15/flow_v0.119.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moesif-express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'moesif-express' {
  declare module.exports: any;
}
