// flow-typed signature: bdd46ac4d3bb648cf02931cc148da549
// flow-typed version: <<STUB>>/moesif-nodejs_v3.3.2/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moesif-nodejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'moesif-nodejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'moesif-nodejs/app' {
  declare module.exports: any;
}

declare module 'moesif-nodejs/lib/batcher' {
  declare module.exports: any;
}

declare module 'moesif-nodejs/lib/dataUtils' {
  declare module.exports: any;
}

declare module 'moesif-nodejs/lib/ensureValidUtils' {
  declare module.exports: any;
}

declare module 'moesif-nodejs/lib/formatEventDataAndSave' {
  declare module.exports: any;
}

declare module 'moesif-nodejs/lib/getRawBody' {
  declare module.exports: any;
}

declare module 'moesif-nodejs/lib' {
  declare module.exports: any;
}

declare module 'moesif-nodejs/lib/moesifConfigManager' {
  declare module.exports: any;
}

declare module 'moesif-nodejs/lib/outgoing' {
  declare module.exports: any;
}

declare module 'moesif-nodejs/lib/outgoingRecorder' {
  declare module.exports: any;
}

declare module 'moesif-nodejs/test/batcherUnit' {
  declare module.exports: any;
}

declare module 'moesif-nodejs/test/mockserver' {
  declare module.exports: any;
}

declare module 'moesif-nodejs/test/outgoingUnit' {
  declare module.exports: any;
}

declare module 'moesif-nodejs/test/outgoingWithMoesif' {
  declare module.exports: any;
}

declare module 'moesif-nodejs/test/outgoingWithMoesifExpress' {
  declare module.exports: any;
}

declare module 'moesif-nodejs/test/testUpdatingEntities' {
  declare module.exports: any;
}

declare module 'moesif-nodejs/test/testUtils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'moesif-nodejs/app.js' {
  declare module.exports: $Exports<'moesif-nodejs/app'>;
}
declare module 'moesif-nodejs/lib/batcher.js' {
  declare module.exports: $Exports<'moesif-nodejs/lib/batcher'>;
}
declare module 'moesif-nodejs/lib/dataUtils.js' {
  declare module.exports: $Exports<'moesif-nodejs/lib/dataUtils'>;
}
declare module 'moesif-nodejs/lib/ensureValidUtils.js' {
  declare module.exports: $Exports<'moesif-nodejs/lib/ensureValidUtils'>;
}
declare module 'moesif-nodejs/lib/formatEventDataAndSave.js' {
  declare module.exports: $Exports<'moesif-nodejs/lib/formatEventDataAndSave'>;
}
declare module 'moesif-nodejs/lib/getRawBody.js' {
  declare module.exports: $Exports<'moesif-nodejs/lib/getRawBody'>;
}
declare module 'moesif-nodejs/lib/index' {
  declare module.exports: $Exports<'moesif-nodejs/lib'>;
}
declare module 'moesif-nodejs/lib/index.js' {
  declare module.exports: $Exports<'moesif-nodejs/lib'>;
}
declare module 'moesif-nodejs/lib/moesifConfigManager.js' {
  declare module.exports: $Exports<'moesif-nodejs/lib/moesifConfigManager'>;
}
declare module 'moesif-nodejs/lib/outgoing.js' {
  declare module.exports: $Exports<'moesif-nodejs/lib/outgoing'>;
}
declare module 'moesif-nodejs/lib/outgoingRecorder.js' {
  declare module.exports: $Exports<'moesif-nodejs/lib/outgoingRecorder'>;
}
declare module 'moesif-nodejs/test/batcherUnit.js' {
  declare module.exports: $Exports<'moesif-nodejs/test/batcherUnit'>;
}
declare module 'moesif-nodejs/test/mockserver.js' {
  declare module.exports: $Exports<'moesif-nodejs/test/mockserver'>;
}
declare module 'moesif-nodejs/test/outgoingUnit.js' {
  declare module.exports: $Exports<'moesif-nodejs/test/outgoingUnit'>;
}
declare module 'moesif-nodejs/test/outgoingWithMoesif.js' {
  declare module.exports: $Exports<'moesif-nodejs/test/outgoingWithMoesif'>;
}
declare module 'moesif-nodejs/test/outgoingWithMoesifExpress.js' {
  declare module.exports: $Exports<'moesif-nodejs/test/outgoingWithMoesifExpress'>;
}
declare module 'moesif-nodejs/test/testUpdatingEntities.js' {
  declare module.exports: $Exports<'moesif-nodejs/test/testUpdatingEntities'>;
}
declare module 'moesif-nodejs/test/testUtils.js' {
  declare module.exports: $Exports<'moesif-nodejs/test/testUtils'>;
}
