// flow-typed signature: 6349e9ebbab82d9dc8a2bbeb0644992d
// flow-typed version: <<STUB>>/next-cookies_v2.0.3/flow_v0.115.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-cookies'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-cookies' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'next-cookies/index' {
  declare module.exports: $Exports<'next-cookies'>;
}
declare module 'next-cookies/index.js' {
  declare module.exports: $Exports<'next-cookies'>;
}
