// flow-typed signature: 121fef665ebb624b9a04c880df2223e2
// flow-typed version: <<STUB>>/next-axiom_v0.13.0/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-axiom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-axiom' {
  declare module.exports: any;
}
