// flow-typed signature: 4308704bb865692ce35f1082a850220b
// flow-typed version: <<STUB>>/notistack_v0.9.9/flow_v0.121.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'notistack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'notistack' {
  declare module.exports: any;
}
