// flow-typed signature: 376d35385cba5c75f6f7e042ac4a6f40
// flow-typed version: <<STUB>>/o9n_v2.1.1/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'o9n'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'o9n' {
  declare module.exports: any;
}
