// flow-typed signature: 88cd47ac0b8a67323939ad376abca545
// flow-typed version: <<STUB>>/react-with-firebase-auth_v1.2.0/flow_v0.112.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-with-firebase-auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-with-firebase-auth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-with-firebase-auth/dist/index.es' {
  declare module.exports: any;
}

declare module 'react-with-firebase-auth/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-with-firebase-auth/dist/index.es.js' {
  declare module.exports: $Exports<'react-with-firebase-auth/dist/index.es'>;
}
declare module 'react-with-firebase-auth/dist/index' {
  declare module.exports: $Exports<'react-with-firebase-auth/dist'>;
}
declare module 'react-with-firebase-auth/dist/index.js' {
  declare module.exports: $Exports<'react-with-firebase-auth/dist'>;
}
