// flow-typed signature: ffc536e0d05394b0351beb6f7c9ea0c8
// flow-typed version: <<STUB>>/react-auth-code-input_v3.2.1/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-auth-code-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-auth-code-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-auth-code-input/dist' {
  declare module.exports: any;
}

declare module 'react-auth-code-input/dist/index.modern' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-auth-code-input/dist/index' {
  declare module.exports: $Exports<'react-auth-code-input/dist'>;
}
declare module 'react-auth-code-input/dist/index.js' {
  declare module.exports: $Exports<'react-auth-code-input/dist'>;
}
declare module 'react-auth-code-input/dist/index.modern.js' {
  declare module.exports: $Exports<'react-auth-code-input/dist/index.modern'>;
}
