// flow-typed signature: c4a9a63af3309f20769060fe43105083
// flow-typed version: <<STUB>>/react-zoom-pan-pinch_v1.6.1/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-zoom-pan-pinch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-zoom-pan-pinch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-zoom-pan-pinch/dist/index.es' {
  declare module.exports: any;
}

declare module 'react-zoom-pan-pinch/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-zoom-pan-pinch/dist/index.es.js' {
  declare module.exports: $Exports<'react-zoom-pan-pinch/dist/index.es'>;
}
declare module 'react-zoom-pan-pinch/dist/index' {
  declare module.exports: $Exports<'react-zoom-pan-pinch/dist'>;
}
declare module 'react-zoom-pan-pinch/dist/index.js' {
  declare module.exports: $Exports<'react-zoom-pan-pinch/dist'>;
}
