// flow-typed signature: 7c2c558e93057459628806f9990c0a19
// flow-typed version: <<STUB>>/@feedback-fish/react_v1.2.1/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@feedback-fish/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@feedback-fish/react' {
  declare module.exports: any;
}
