// flow-typed signature: ab327116209a9300026d4826daca2c35
// flow-typed version: <<STUB>>/@stripe/react-stripe-js_v2.1.0/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@stripe/react-stripe-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@stripe/react-stripe-js' {
  declare module.exports: any;
}
