// flow-typed signature: d5931d0efed69b7add2f060dcd5fc25b
// flow-typed version: <<STUB>>/@stripe/stripe-js_v1.44.1/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@stripe/stripe-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@stripe/stripe-js' {
  declare module.exports: any;
}
