// flow-typed signature: b46e8a54ac3b71b0d0779d73a25071d1
// flow-typed version: <<STUB>>/@power-rent/ui_v2.0.4/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@power-rent/ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@power-rent/ui" {
  declare module.exports: any;
}
declare module "@power-rent/ui/components" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@power-rent/ui/components/AddressGoogleAutocomplete" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Badge" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/BottomWidget" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Breadcrumbs" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Button" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Buttons/Default" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/CarCard" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Card" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Cards/ColumnCard" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Cards/ServiceCard" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Cards/VehicleCard" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Cards/VehicleCard/VehicleContent" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/CardsWidget" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Carousel" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/CarsResults/CarItem" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/CarsResults/CarsResults" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/CarsResults/types" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/ChangeCarWidget" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/CharacteristicsCards" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Containers/CardsWrapperContainer" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Containers/LayerContainer" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/CustomImage" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/ExtraOptions/ExtraOption" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/ExtraOptions/ExtraOptions" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/ExtraOptions/types" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/FinalStepWidget" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Footer" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/FooterNav/ContactItem" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/FooterNav/FooterContacts" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/FooterNav/FooterNav" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Form" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/GallerySlider/GalleryDots" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/GallerySlider" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Header" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/HeaderNav/BurgerMenu" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/HeaderNav/BurgerMenu/NavList" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/HeaderNav/HeaderNav" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/HeaderNav/HeaderTop" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/components" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Input" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/InputWithError" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/ItemsList" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/ItemsWidget" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/LabeledSwitch" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Link" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/MainImageBlock" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/NextPrev" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/OptionalDetails" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/OrderDetails" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/PasswordInput" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/PaymentMethod" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/PickupDropoff" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Range" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/SecurityDeposit" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/SuccessOrder" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/SupportPhone" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/AccelerationIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/ArrowDownSmall" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/ArrowLeftBlueIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/ArrowLeftIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/ArrowRightBlueIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/ArrowRightIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/BabyIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/ButtonNext" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/ButtonPrev" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/CheckmarkIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/CheckmarkInCircle" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/CloseIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/CogIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/DashedLine" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/DropOffPoint" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/EngineIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/footer/EmaiIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/footer/MarkerIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/footer/PhoneIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/footer/PhoneWhiteIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/GasPumpIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/HiddenEye" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/LocationIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/PasswordEye" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/PhoneIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/PickupPoint" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/PlusIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/PlusSimpleIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/PowerIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/QuestionIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/SeatsIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/SeatsIcon2" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/SkiingIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/SpeedIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/Star" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/svg/WhatsappIcon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Text" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/TextBlock" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/TextWidget" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/TopCar" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/TopCars" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/UploadPhoto" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Variants/ImagesVariants" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Variants" {
  declare module.exports: any;
}

declare module "@power-rent/ui/components/Variants/Variants" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/hooks" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/hooks/useClickOutside" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/hooks/useDragAndDrop" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/hooks/useGoogle" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/hooks/useSwipe" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/hooks/useWindowSize" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/mock" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/pages/_app" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/pages/_document" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/pages/api/hello" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/pages/faq" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/pages" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/AddressGoogleAutocomplete.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/BottomWidget.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/Button.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/CarsResults.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/ChangeCarWidget.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/CharacteristicsCards.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/ExtraOptions.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/FinalStepWidget.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/Form.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/GallerySlider.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/ImagesVariants.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/Input.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/InputWithError.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/LabeledSwitch.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/OptionalDetails.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/OrderDetails.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/PasswordInput.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/PaymentMethod.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/PickupDropoff.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/Range.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/SuccessOrder.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/SupportPhone.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/TopCar.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/TopCars.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/UploadPhoto.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/Variants.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/stories/VehicleCard.stories" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/styles" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/theme/button" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/theme/container" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/theme" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/theme/other" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/theme/palette" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/theme/text" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/types/Card" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/types/Icon" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/types/Item" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/types/vehicle" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/utils/addLeadingZero" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/utils/constants" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/utils/constructFrom" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/utils/format" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/utils/formatters" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/utils/getHours" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/utils/getWeek" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/utils/getWeekYear" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/utils" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/utils/startOfWeek" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/utils/startOfWeekYear" {
  declare module.exports: any;
}

declare module "@power-rent/ui/dist/utils/toDate" {
  declare module.exports: any;
}

declare module "@power-rent/ui/next.config" {
  declare module.exports: any;
}

declare module "@power-rent/ui/styles" {
  declare module.exports: any;
}

// Filename aliases
declare module "@power-rent/ui/components/AddressGoogleAutocomplete.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/AddressGoogleAutocomplete">;
}
declare module "@power-rent/ui/components/Badge.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Badge">;
}
declare module "@power-rent/ui/components/BottomWidget.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/BottomWidget">;
}
declare module "@power-rent/ui/components/Breadcrumbs.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Breadcrumbs">;
}
declare module "@power-rent/ui/components/Button.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Button">;
}
declare module "@power-rent/ui/components/Buttons/Default.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Buttons/Default">;
}
declare module "@power-rent/ui/components/CarCard.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/CarCard">;
}
declare module "@power-rent/ui/components/Card.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Card">;
}
declare module "@power-rent/ui/components/Cards/ColumnCard.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Cards/ColumnCard">;
}
declare module "@power-rent/ui/components/Cards/ServiceCard.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Cards/ServiceCard">;
}
declare module "@power-rent/ui/components/Cards/VehicleCard/index" {
  declare module.exports: $Exports<"@power-rent/ui/components/Cards/VehicleCard">;
}
declare module "@power-rent/ui/components/Cards/VehicleCard/index.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Cards/VehicleCard">;
}
declare module "@power-rent/ui/components/Cards/VehicleCard/VehicleContent.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Cards/VehicleCard/VehicleContent">;
}
declare module "@power-rent/ui/components/CardsWidget.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/CardsWidget">;
}
declare module "@power-rent/ui/components/Carousel.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Carousel">;
}
declare module "@power-rent/ui/components/CarsResults/CarItem.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/CarsResults/CarItem">;
}
declare module "@power-rent/ui/components/CarsResults/CarsResults.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/CarsResults/CarsResults">;
}
declare module "@power-rent/ui/components/CarsResults/types.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/CarsResults/types">;
}
declare module "@power-rent/ui/components/ChangeCarWidget.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/ChangeCarWidget">;
}
declare module "@power-rent/ui/components/CharacteristicsCards.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/CharacteristicsCards">;
}
declare module "@power-rent/ui/components/Containers/CardsWrapperContainer.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Containers/CardsWrapperContainer">;
}
declare module "@power-rent/ui/components/Containers/LayerContainer.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Containers/LayerContainer">;
}
declare module "@power-rent/ui/components/CustomImage.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/CustomImage">;
}
declare module "@power-rent/ui/components/ExtraOptions/ExtraOption.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/ExtraOptions/ExtraOption">;
}
declare module "@power-rent/ui/components/ExtraOptions/ExtraOptions.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/ExtraOptions/ExtraOptions">;
}
declare module "@power-rent/ui/components/ExtraOptions/types.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/ExtraOptions/types">;
}
declare module "@power-rent/ui/components/FinalStepWidget.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/FinalStepWidget">;
}
declare module "@power-rent/ui/components/Footer.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Footer">;
}
declare module "@power-rent/ui/components/FooterNav/ContactItem.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/FooterNav/ContactItem">;
}
declare module "@power-rent/ui/components/FooterNav/FooterContacts.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/FooterNav/FooterContacts">;
}
declare module "@power-rent/ui/components/FooterNav/FooterNav.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/FooterNav/FooterNav">;
}
declare module "@power-rent/ui/components/Form.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Form">;
}
declare module "@power-rent/ui/components/GallerySlider/GalleryDots.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/GallerySlider/GalleryDots">;
}
declare module "@power-rent/ui/components/GallerySlider/index" {
  declare module.exports: $Exports<"@power-rent/ui/components/GallerySlider">;
}
declare module "@power-rent/ui/components/GallerySlider/index.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/GallerySlider">;
}
declare module "@power-rent/ui/components/Header.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Header">;
}
declare module "@power-rent/ui/components/HeaderNav/BurgerMenu/index" {
  declare module.exports: $Exports<"@power-rent/ui/components/HeaderNav/BurgerMenu">;
}
declare module "@power-rent/ui/components/HeaderNav/BurgerMenu/index.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/HeaderNav/BurgerMenu">;
}
declare module "@power-rent/ui/components/HeaderNav/BurgerMenu/NavList.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/HeaderNav/BurgerMenu/NavList">;
}
declare module "@power-rent/ui/components/HeaderNav/HeaderNav.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/HeaderNav/HeaderNav">;
}
declare module "@power-rent/ui/components/HeaderNav/HeaderTop.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/HeaderNav/HeaderTop">;
}
declare module "@power-rent/ui/components/index" {
  declare module.exports: $Exports<"@power-rent/ui/dist/components">;
}
declare module "@power-rent/ui/components/index.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/components">;
}
declare module "@power-rent/ui/components/Input.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Input">;
}
declare module "@power-rent/ui/components/InputWithError.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/InputWithError">;
}
declare module "@power-rent/ui/components/ItemsList.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/ItemsList">;
}
declare module "@power-rent/ui/components/ItemsWidget.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/ItemsWidget">;
}
declare module "@power-rent/ui/components/LabeledSwitch.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/LabeledSwitch">;
}
declare module "@power-rent/ui/components/Link.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Link">;
}
declare module "@power-rent/ui/components/MainImageBlock.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/MainImageBlock">;
}
declare module "@power-rent/ui/components/NextPrev.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/NextPrev">;
}
declare module "@power-rent/ui/components/OptionalDetails.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/OptionalDetails">;
}
declare module "@power-rent/ui/components/OrderDetails.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/OrderDetails">;
}
declare module "@power-rent/ui/components/PasswordInput.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/PasswordInput">;
}
declare module "@power-rent/ui/components/PaymentMethod.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/PaymentMethod">;
}
declare module "@power-rent/ui/components/PickupDropoff.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/PickupDropoff">;
}
declare module "@power-rent/ui/components/Range.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Range">;
}
declare module "@power-rent/ui/components/SecurityDeposit.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/SecurityDeposit">;
}
declare module "@power-rent/ui/components/SuccessOrder.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/SuccessOrder">;
}
declare module "@power-rent/ui/components/SupportPhone.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/SupportPhone">;
}
declare module "@power-rent/ui/components/svg/AccelerationIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/AccelerationIcon">;
}
declare module "@power-rent/ui/components/svg/ArrowDownSmall.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/ArrowDownSmall">;
}
declare module "@power-rent/ui/components/svg/ArrowLeftBlueIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/ArrowLeftBlueIcon">;
}
declare module "@power-rent/ui/components/svg/ArrowLeftIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/ArrowLeftIcon">;
}
declare module "@power-rent/ui/components/svg/ArrowRightBlueIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/ArrowRightBlueIcon">;
}
declare module "@power-rent/ui/components/svg/ArrowRightIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/ArrowRightIcon">;
}
declare module "@power-rent/ui/components/svg/BabyIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/BabyIcon">;
}
declare module "@power-rent/ui/components/svg/ButtonNext.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/ButtonNext">;
}
declare module "@power-rent/ui/components/svg/ButtonPrev.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/ButtonPrev">;
}
declare module "@power-rent/ui/components/svg/CheckmarkIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/CheckmarkIcon">;
}
declare module "@power-rent/ui/components/svg/CheckmarkInCircle.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/CheckmarkInCircle">;
}
declare module "@power-rent/ui/components/svg/CloseIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/CloseIcon">;
}
declare module "@power-rent/ui/components/svg/CogIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/CogIcon">;
}
declare module "@power-rent/ui/components/svg/DashedLine.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/DashedLine">;
}
declare module "@power-rent/ui/components/svg/DropOffPoint.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/DropOffPoint">;
}
declare module "@power-rent/ui/components/svg/EngineIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/EngineIcon">;
}
declare module "@power-rent/ui/components/svg/footer/EmaiIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/footer/EmaiIcon">;
}
declare module "@power-rent/ui/components/svg/footer/MarkerIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/footer/MarkerIcon">;
}
declare module "@power-rent/ui/components/svg/footer/PhoneIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/footer/PhoneIcon">;
}
declare module "@power-rent/ui/components/svg/footer/PhoneWhiteIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/footer/PhoneWhiteIcon">;
}
declare module "@power-rent/ui/components/svg/GasPumpIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/GasPumpIcon">;
}
declare module "@power-rent/ui/components/svg/HiddenEye.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/HiddenEye">;
}
declare module "@power-rent/ui/components/svg/index" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg">;
}
declare module "@power-rent/ui/components/svg/index.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg">;
}
declare module "@power-rent/ui/components/svg/LocationIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/LocationIcon">;
}
declare module "@power-rent/ui/components/svg/PasswordEye.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/PasswordEye">;
}
declare module "@power-rent/ui/components/svg/PhoneIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/PhoneIcon">;
}
declare module "@power-rent/ui/components/svg/PickupPoint.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/PickupPoint">;
}
declare module "@power-rent/ui/components/svg/PlusIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/PlusIcon">;
}
declare module "@power-rent/ui/components/svg/PlusSimpleIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/PlusSimpleIcon">;
}
declare module "@power-rent/ui/components/svg/PowerIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/PowerIcon">;
}
declare module "@power-rent/ui/components/svg/QuestionIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/QuestionIcon">;
}
declare module "@power-rent/ui/components/svg/SeatsIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/SeatsIcon">;
}
declare module "@power-rent/ui/components/svg/SeatsIcon2.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/SeatsIcon2">;
}
declare module "@power-rent/ui/components/svg/SkiingIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/SkiingIcon">;
}
declare module "@power-rent/ui/components/svg/SpeedIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/SpeedIcon">;
}
declare module "@power-rent/ui/components/svg/Star.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/Star">;
}
declare module "@power-rent/ui/components/svg/WhatsappIcon.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/svg/WhatsappIcon">;
}
declare module "@power-rent/ui/components/Text.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Text">;
}
declare module "@power-rent/ui/components/TextBlock.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/TextBlock">;
}
declare module "@power-rent/ui/components/TextWidget.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/TextWidget">;
}
declare module "@power-rent/ui/components/TopCar.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/TopCar">;
}
declare module "@power-rent/ui/components/TopCars.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/TopCars">;
}
declare module "@power-rent/ui/components/UploadPhoto.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/UploadPhoto">;
}
declare module "@power-rent/ui/components/Variants/ImagesVariants.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Variants/ImagesVariants">;
}
declare module "@power-rent/ui/components/Variants/index" {
  declare module.exports: $Exports<"@power-rent/ui/components/Variants">;
}
declare module "@power-rent/ui/components/Variants/index.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Variants">;
}
declare module "@power-rent/ui/components/Variants/Variants.js" {
  declare module.exports: $Exports<"@power-rent/ui/components/Variants/Variants">;
}
declare module "@power-rent/ui/dist/hooks/index" {
  declare module.exports: $Exports<"@power-rent/ui/dist/hooks">;
}
declare module "@power-rent/ui/dist/hooks/index.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/hooks">;
}
declare module "@power-rent/ui/dist/hooks/useClickOutside.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/hooks/useClickOutside">;
}
declare module "@power-rent/ui/dist/hooks/useDragAndDrop.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/hooks/useDragAndDrop">;
}
declare module "@power-rent/ui/dist/hooks/useGoogle.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/hooks/useGoogle">;
}
declare module "@power-rent/ui/dist/hooks/useSwipe.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/hooks/useSwipe">;
}
declare module "@power-rent/ui/dist/hooks/useWindowSize.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/hooks/useWindowSize">;
}
declare module "@power-rent/ui/dist/mock/index" {
  declare module.exports: $Exports<"@power-rent/ui/dist/mock">;
}
declare module "@power-rent/ui/dist/mock/index.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/mock">;
}
declare module "@power-rent/ui/dist/pages/_app.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/pages/_app">;
}
declare module "@power-rent/ui/dist/pages/_document.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/pages/_document">;
}
declare module "@power-rent/ui/dist/pages/api/hello.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/pages/api/hello">;
}
declare module "@power-rent/ui/dist/pages/faq.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/pages/faq">;
}
declare module "@power-rent/ui/dist/pages/index" {
  declare module.exports: $Exports<"@power-rent/ui/dist/pages">;
}
declare module "@power-rent/ui/dist/pages/index.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/pages">;
}
declare module "@power-rent/ui/dist/stories/AddressGoogleAutocomplete.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/AddressGoogleAutocomplete.stories">;
}
declare module "@power-rent/ui/dist/stories/BottomWidget.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/BottomWidget.stories">;
}
declare module "@power-rent/ui/dist/stories/Button.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/Button.stories">;
}
declare module "@power-rent/ui/dist/stories/CarsResults.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/CarsResults.stories">;
}
declare module "@power-rent/ui/dist/stories/ChangeCarWidget.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/ChangeCarWidget.stories">;
}
declare module "@power-rent/ui/dist/stories/CharacteristicsCards.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/CharacteristicsCards.stories">;
}
declare module "@power-rent/ui/dist/stories/ExtraOptions.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/ExtraOptions.stories">;
}
declare module "@power-rent/ui/dist/stories/FinalStepWidget.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/FinalStepWidget.stories">;
}
declare module "@power-rent/ui/dist/stories/Form.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/Form.stories">;
}
declare module "@power-rent/ui/dist/stories/GallerySlider.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/GallerySlider.stories">;
}
declare module "@power-rent/ui/dist/stories/ImagesVariants.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/ImagesVariants.stories">;
}
declare module "@power-rent/ui/dist/stories/Input.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/Input.stories">;
}
declare module "@power-rent/ui/dist/stories/InputWithError.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/InputWithError.stories">;
}
declare module "@power-rent/ui/dist/stories/LabeledSwitch.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/LabeledSwitch.stories">;
}
declare module "@power-rent/ui/dist/stories/OptionalDetails.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/OptionalDetails.stories">;
}
declare module "@power-rent/ui/dist/stories/OrderDetails.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/OrderDetails.stories">;
}
declare module "@power-rent/ui/dist/stories/PasswordInput.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/PasswordInput.stories">;
}
declare module "@power-rent/ui/dist/stories/PaymentMethod.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/PaymentMethod.stories">;
}
declare module "@power-rent/ui/dist/stories/PickupDropoff.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/PickupDropoff.stories">;
}
declare module "@power-rent/ui/dist/stories/Range.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/Range.stories">;
}
declare module "@power-rent/ui/dist/stories/SuccessOrder.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/SuccessOrder.stories">;
}
declare module "@power-rent/ui/dist/stories/SupportPhone.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/SupportPhone.stories">;
}
declare module "@power-rent/ui/dist/stories/TopCar.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/TopCar.stories">;
}
declare module "@power-rent/ui/dist/stories/TopCars.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/TopCars.stories">;
}
declare module "@power-rent/ui/dist/stories/UploadPhoto.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/UploadPhoto.stories">;
}
declare module "@power-rent/ui/dist/stories/Variants.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/Variants.stories">;
}
declare module "@power-rent/ui/dist/stories/VehicleCard.stories.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/stories/VehicleCard.stories">;
}
declare module "@power-rent/ui/dist/styles/index" {
  declare module.exports: $Exports<"@power-rent/ui/dist/styles">;
}
declare module "@power-rent/ui/dist/styles/index.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/styles">;
}
declare module "@power-rent/ui/dist/theme/button.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/theme/button">;
}
declare module "@power-rent/ui/dist/theme/container.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/theme/container">;
}
declare module "@power-rent/ui/dist/theme/index" {
  declare module.exports: $Exports<"@power-rent/ui/dist/theme">;
}
declare module "@power-rent/ui/dist/theme/index.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/theme">;
}
declare module "@power-rent/ui/dist/theme/other.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/theme/other">;
}
declare module "@power-rent/ui/dist/theme/palette.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/theme/palette">;
}
declare module "@power-rent/ui/dist/theme/text.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/theme/text">;
}
declare module "@power-rent/ui/dist/types/Card.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/types/Card">;
}
declare module "@power-rent/ui/dist/types/Icon.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/types/Icon">;
}
declare module "@power-rent/ui/dist/types/Item.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/types/Item">;
}
declare module "@power-rent/ui/dist/types/vehicle.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/types/vehicle">;
}
declare module "@power-rent/ui/dist/utils/addLeadingZero.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/utils/addLeadingZero">;
}
declare module "@power-rent/ui/dist/utils/constants/index" {
  declare module.exports: $Exports<"@power-rent/ui/dist/utils/constants">;
}
declare module "@power-rent/ui/dist/utils/constants/index.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/utils/constants">;
}
declare module "@power-rent/ui/dist/utils/constructFrom.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/utils/constructFrom">;
}
declare module "@power-rent/ui/dist/utils/format.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/utils/format">;
}
declare module "@power-rent/ui/dist/utils/formatters.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/utils/formatters">;
}
declare module "@power-rent/ui/dist/utils/getHours.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/utils/getHours">;
}
declare module "@power-rent/ui/dist/utils/getWeek.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/utils/getWeek">;
}
declare module "@power-rent/ui/dist/utils/getWeekYear.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/utils/getWeekYear">;
}
declare module "@power-rent/ui/dist/utils/index" {
  declare module.exports: $Exports<"@power-rent/ui/dist/utils">;
}
declare module "@power-rent/ui/dist/utils/index.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/utils">;
}
declare module "@power-rent/ui/dist/utils/startOfWeek.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/utils/startOfWeek">;
}
declare module "@power-rent/ui/dist/utils/startOfWeekYear.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/utils/startOfWeekYear">;
}
declare module "@power-rent/ui/dist/utils/toDate.js" {
  declare module.exports: $Exports<"@power-rent/ui/dist/utils/toDate">;
}
declare module "@power-rent/ui/next.config.js" {
  declare module.exports: $Exports<"@power-rent/ui/next.config">;
}
declare module "@power-rent/ui/styles/index" {
  declare module.exports: $Exports<"@power-rent/ui/styles">;
}
declare module "@power-rent/ui/styles/index.js" {
  declare module.exports: $Exports<"@power-rent/ui/styles">;
}
