// flow-typed signature: d5fcd91ea875bbf91b465b1a5151c179
// flow-typed version: <<STUB>>/@power-rent/widget_v2.8.7/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@power-rent/widget'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@power-rent/widget" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@power-rent/widget/build" {
  declare module.exports: any;
}

declare module "@power-rent/widget/dev-server" {
  declare module.exports: any;
}

declare module "@power-rent/widget/dist" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/@babel/cli_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/@babel/core_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/@babel/eslint-parser_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/@babel/preset-env_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/@babel/preset-flow_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/@babel/preset-react_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/@emotion/babel-preset-css-prop_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/@octokit/rest_v18.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/@power-rent/data-validation_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/@tgrx/getcontrasttext_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/babel-eslint_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/babel-jest_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/babel-loader_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/babel-plugin-inline-react-svg_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/babel-plugin-react-intl_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/classnames_v2.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/colors_v1.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/compression-webpack-plugin_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/css-loader_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/css-minimizer-webpack-plugin_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/eslint_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/eslint-config-airbnb_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/eslint-plugin-flowtype_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/eslint-plugin-import_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/eslint-plugin-react_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/eslint-plugin-react-hooks_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/express_v4.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/flow-bin_v0.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/fs-extra_v8.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/glob_v7.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/hoist-non-react-statics_v3.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/image-webpack-loader_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/jest_v27.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/lodash_v4.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/md5_v2.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/mini-css-extract-plugin_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/mkdirp_v1.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/moment_v2.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/node-fetch_v1.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/node-stream-zip_v1.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/preact_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/prettier_v1.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/purgecss-webpack-plugin_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/react-date-range_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/react-dom_v18.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/rimraf_v3.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/sass-loader_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/semver_v7.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/sinon_v7.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/style-loader_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/webpack_v5.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/webpack-bundle-analyzer_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/webpack-cli_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/webpack-dev-middleware_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/webpack-dev-server_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/webpack-merge_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/yargs_v15.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/flow-typed/npm/zustand_vx.x.x" {
  declare module.exports: any;
}

declare module "@power-rent/widget/global.flow" {
  declare module.exports: any;
}

declare module "@power-rent/widget/next-app/next.config" {
  declare module.exports: any;
}

declare module "@power-rent/widget/next-app/pages/_app" {
  declare module.exports: any;
}

declare module "@power-rent/widget/next-app/pages/_document" {
  declare module.exports: any;
}

declare module "@power-rent/widget/next-app/pages/api/hello" {
  declare module.exports: any;
}

declare module "@power-rent/widget/next-app/pages/api/public/widget/horizontal-toprent-app-booking-widget.js.gz" {
  declare module.exports: any;
}

declare module "@power-rent/widget/next-app/pages/api/public/widget/horizontal-toprent-app-booking-widget.js" {
  declare module.exports: any;
}

declare module "@power-rent/widget/next-app/pages" {
  declare module.exports: any;
}

declare module "@power-rent/widget/sandbox" {
  declare module.exports: any;
}

declare module "@power-rent/widget/webpack/webpack.analyze.config" {
  declare module.exports: any;
}

declare module "@power-rent/widget/webpack/webpack.common.config" {
  declare module.exports: any;
}

declare module "@power-rent/widget/webpack/webpack.dev.config" {
  declare module.exports: any;
}

declare module "@power-rent/widget/webpack/webpack.prod.config" {
  declare module.exports: any;
}

declare module "@power-rent/widget/webpack/webpack.react.config" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/AddressInput" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/AddressInput/initGoogleService" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/ClosedWidget" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/constants" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/CustomCheckbox" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/CustomSelect" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/DateInput" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/DateRangeStyled/allCss" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/DateRangeStyled" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/icons/Arrow" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/icons/DateIcon" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/icons/DateIcon2" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/icons/LocationIcon" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/icons/TimeIcon" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/icons/TimeIcon2" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/Loader" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/SearchButton" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/store" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/StylesConfig" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/StylesConfig/shade" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/StylesConfig/simple" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/StylesConfig/white" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/StylesConfig/widget" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/TimeInput" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/useWidgetInit" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/useWindowSize" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/utils/dateTransform/addDays" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/utils/dateTransform/addLeadingZero" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/utils/dateTransform/constants" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/utils/dateTransform/constructFrom" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/utils/dateTransform/format" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/utils/dateTransform/getDay" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/utils/dateTransform/getHours" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/utils/dateTransform/getMinutes" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/utils/dateTransform/getWeek" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/utils/dateTransform/getWeekYear" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/utils/dateTransform" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/utils/dateTransform/isDate" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/utils/dateTransform/isValid" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/utils/dateTransform/lib/formatters" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/utils/dateTransform/setHours" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/utils/dateTransform/setMinutes" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/utils/dateTransform/startOfWeek" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/utils/dateTransform/startOfWeekYear" {
  declare module.exports: any;
}

declare module "@power-rent/widget/Widget/utils/dateTransform/toDate" {
  declare module.exports: any;
}

// Filename aliases
declare module "@power-rent/widget/build/index" {
  declare module.exports: $Exports<"@power-rent/widget/build">;
}
declare module "@power-rent/widget/build/index.js" {
  declare module.exports: $Exports<"@power-rent/widget/build">;
}
declare module "@power-rent/widget/dev-server.js" {
  declare module.exports: $Exports<"@power-rent/widget/dev-server">;
}
declare module "@power-rent/widget/dist/index" {
  declare module.exports: $Exports<"@power-rent/widget/dist">;
}
declare module "@power-rent/widget/dist/index.js" {
  declare module.exports: $Exports<"@power-rent/widget/dist">;
}
declare module "@power-rent/widget/flow-typed/npm/@babel/cli_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/@babel/cli_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/@babel/core_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/@babel/core_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/@babel/eslint-parser_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/@babel/eslint-parser_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/@babel/preset-env_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/@babel/preset-env_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/@babel/preset-flow_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/@babel/preset-flow_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/@babel/preset-react_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/@babel/preset-react_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/@emotion/babel-preset-css-prop_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/@emotion/babel-preset-css-prop_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/@octokit/rest_v18.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/@octokit/rest_v18.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/@power-rent/data-validation_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/@power-rent/data-validation_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/@tgrx/getcontrasttext_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/@tgrx/getcontrasttext_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/babel-eslint_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/babel-eslint_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/babel-jest_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/babel-jest_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/babel-loader_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/babel-loader_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/babel-plugin-inline-react-svg_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/babel-plugin-inline-react-svg_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/babel-plugin-react-intl_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/babel-plugin-react-intl_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/classnames_v2.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/classnames_v2.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/colors_v1.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/colors_v1.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/compression-webpack-plugin_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/compression-webpack-plugin_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/css-loader_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/css-loader_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/css-minimizer-webpack-plugin_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/css-minimizer-webpack-plugin_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/eslint_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/eslint_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/eslint-config-airbnb_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/eslint-config-airbnb_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/eslint-plugin-flowtype_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/eslint-plugin-import_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/eslint-plugin-import_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/eslint-plugin-react_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/eslint-plugin-react_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/eslint-plugin-react-hooks_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/eslint-plugin-react-hooks_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/express_v4.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/express_v4.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/flow-bin_v0.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/flow-bin_v0.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/fs-extra_v8.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/fs-extra_v8.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/glob_v7.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/glob_v7.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/hoist-non-react-statics_v3.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/hoist-non-react-statics_v3.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/image-webpack-loader_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/image-webpack-loader_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/jest_v27.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/jest_v27.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/lodash_v4.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/lodash_v4.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/md5_v2.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/md5_v2.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/mini-css-extract-plugin_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/mini-css-extract-plugin_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/mkdirp_v1.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/mkdirp_v1.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/moment_v2.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/moment_v2.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/node-fetch_v1.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/node-fetch_v1.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/node-stream-zip_v1.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/node-stream-zip_v1.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/preact_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/preact_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/prettier_v1.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/prettier_v1.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/purgecss-webpack-plugin_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/purgecss-webpack-plugin_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/react-date-range_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/react-date-range_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/react-dom_v18.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/react-dom_v18.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/rimraf_v3.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/rimraf_v3.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/sass-loader_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/sass-loader_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/semver_v7.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/semver_v7.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/sinon_v7.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/sinon_v7.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/style-loader_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/style-loader_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/webpack_v5.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/webpack_v5.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/webpack-bundle-analyzer_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/webpack-bundle-analyzer_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/webpack-cli_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/webpack-cli_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/webpack-dev-middleware_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/webpack-dev-middleware_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/webpack-dev-server_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/webpack-dev-server_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/webpack-merge_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/webpack-merge_vx.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/yargs_v15.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/yargs_v15.x.x">;
}
declare module "@power-rent/widget/flow-typed/npm/zustand_vx.x.x.js" {
  declare module.exports: $Exports<"@power-rent/widget/flow-typed/npm/zustand_vx.x.x">;
}
declare module "@power-rent/widget/global.flow.js" {
  declare module.exports: $Exports<"@power-rent/widget/global.flow">;
}
declare module "@power-rent/widget/index" {
  declare module.exports: $Exports<"@power-rent/widget">;
}
declare module "@power-rent/widget/index.js" {
  declare module.exports: $Exports<"@power-rent/widget">;
}
declare module "@power-rent/widget/next-app/next.config.js" {
  declare module.exports: $Exports<"@power-rent/widget/next-app/next.config">;
}
declare module "@power-rent/widget/next-app/pages/_app.js" {
  declare module.exports: $Exports<"@power-rent/widget/next-app/pages/_app">;
}
declare module "@power-rent/widget/next-app/pages/_document.js" {
  declare module.exports: $Exports<"@power-rent/widget/next-app/pages/_document">;
}
declare module "@power-rent/widget/next-app/pages/api/hello.js" {
  declare module.exports: $Exports<"@power-rent/widget/next-app/pages/api/hello">;
}
declare module "@power-rent/widget/next-app/pages/api/public/widget/horizontal-toprent-app-booking-widget.js.gz.js" {
  declare module.exports: $Exports<"@power-rent/widget/next-app/pages/api/public/widget/horizontal-toprent-app-booking-widget.js.gz">;
}
declare module "@power-rent/widget/next-app/pages/api/public/widget/horizontal-toprent-app-booking-widget.js.js" {
  declare module.exports: $Exports<"@power-rent/widget/next-app/pages/api/public/widget/horizontal-toprent-app-booking-widget.js">;
}
declare module "@power-rent/widget/next-app/pages/index" {
  declare module.exports: $Exports<"@power-rent/widget/next-app/pages">;
}
declare module "@power-rent/widget/next-app/pages/index.js" {
  declare module.exports: $Exports<"@power-rent/widget/next-app/pages">;
}
declare module "@power-rent/widget/sandbox/index" {
  declare module.exports: $Exports<"@power-rent/widget/sandbox">;
}
declare module "@power-rent/widget/sandbox/index.js" {
  declare module.exports: $Exports<"@power-rent/widget/sandbox">;
}
declare module "@power-rent/widget/webpack/webpack.analyze.config.js" {
  declare module.exports: $Exports<"@power-rent/widget/webpack/webpack.analyze.config">;
}
declare module "@power-rent/widget/webpack/webpack.common.config.js" {
  declare module.exports: $Exports<"@power-rent/widget/webpack/webpack.common.config">;
}
declare module "@power-rent/widget/webpack/webpack.dev.config.js" {
  declare module.exports: $Exports<"@power-rent/widget/webpack/webpack.dev.config">;
}
declare module "@power-rent/widget/webpack/webpack.prod.config.js" {
  declare module.exports: $Exports<"@power-rent/widget/webpack/webpack.prod.config">;
}
declare module "@power-rent/widget/webpack/webpack.react.config.js" {
  declare module.exports: $Exports<"@power-rent/widget/webpack/webpack.react.config">;
}
declare module "@power-rent/widget/Widget/AddressInput/index" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/AddressInput">;
}
declare module "@power-rent/widget/Widget/AddressInput/index.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/AddressInput">;
}
declare module "@power-rent/widget/Widget/AddressInput/initGoogleService.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/AddressInput/initGoogleService">;
}
declare module "@power-rent/widget/Widget/ClosedWidget/index" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/ClosedWidget">;
}
declare module "@power-rent/widget/Widget/ClosedWidget/index.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/ClosedWidget">;
}
declare module "@power-rent/widget/Widget/constants.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/constants">;
}
declare module "@power-rent/widget/Widget/CustomCheckbox/index" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/CustomCheckbox">;
}
declare module "@power-rent/widget/Widget/CustomCheckbox/index.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/CustomCheckbox">;
}
declare module "@power-rent/widget/Widget/CustomSelect/index" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/CustomSelect">;
}
declare module "@power-rent/widget/Widget/CustomSelect/index.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/CustomSelect">;
}
declare module "@power-rent/widget/Widget/DateInput/index" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/DateInput">;
}
declare module "@power-rent/widget/Widget/DateInput/index.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/DateInput">;
}
declare module "@power-rent/widget/Widget/DateRangeStyled/allCss.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/DateRangeStyled/allCss">;
}
declare module "@power-rent/widget/Widget/DateRangeStyled/index" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/DateRangeStyled">;
}
declare module "@power-rent/widget/Widget/DateRangeStyled/index.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/DateRangeStyled">;
}
declare module "@power-rent/widget/Widget/icons/Arrow.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/icons/Arrow">;
}
declare module "@power-rent/widget/Widget/icons/DateIcon.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/icons/DateIcon">;
}
declare module "@power-rent/widget/Widget/icons/DateIcon2.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/icons/DateIcon2">;
}
declare module "@power-rent/widget/Widget/icons/LocationIcon.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/icons/LocationIcon">;
}
declare module "@power-rent/widget/Widget/icons/TimeIcon.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/icons/TimeIcon">;
}
declare module "@power-rent/widget/Widget/icons/TimeIcon2.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/icons/TimeIcon2">;
}
declare module "@power-rent/widget/Widget/index" {
  declare module.exports: $Exports<"@power-rent/widget/Widget">;
}
declare module "@power-rent/widget/Widget/index.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget">;
}
declare module "@power-rent/widget/Widget/Loader/index" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/Loader">;
}
declare module "@power-rent/widget/Widget/Loader/index.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/Loader">;
}
declare module "@power-rent/widget/Widget/SearchButton/index" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/SearchButton">;
}
declare module "@power-rent/widget/Widget/SearchButton/index.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/SearchButton">;
}
declare module "@power-rent/widget/Widget/store/index" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/store">;
}
declare module "@power-rent/widget/Widget/store/index.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/store">;
}
declare module "@power-rent/widget/Widget/StylesConfig/index" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/StylesConfig">;
}
declare module "@power-rent/widget/Widget/StylesConfig/index.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/StylesConfig">;
}
declare module "@power-rent/widget/Widget/StylesConfig/shade.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/StylesConfig/shade">;
}
declare module "@power-rent/widget/Widget/StylesConfig/simple.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/StylesConfig/simple">;
}
declare module "@power-rent/widget/Widget/StylesConfig/white.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/StylesConfig/white">;
}
declare module "@power-rent/widget/Widget/StylesConfig/widget.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/StylesConfig/widget">;
}
declare module "@power-rent/widget/Widget/TimeInput/index" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/TimeInput">;
}
declare module "@power-rent/widget/Widget/TimeInput/index.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/TimeInput">;
}
declare module "@power-rent/widget/Widget/useWidgetInit.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/useWidgetInit">;
}
declare module "@power-rent/widget/Widget/useWindowSize.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/useWindowSize">;
}
declare module "@power-rent/widget/Widget/utils/dateTransform/addDays.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/utils/dateTransform/addDays">;
}
declare module "@power-rent/widget/Widget/utils/dateTransform/addLeadingZero.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/utils/dateTransform/addLeadingZero">;
}
declare module "@power-rent/widget/Widget/utils/dateTransform/constants/index" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/utils/dateTransform/constants">;
}
declare module "@power-rent/widget/Widget/utils/dateTransform/constants/index.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/utils/dateTransform/constants">;
}
declare module "@power-rent/widget/Widget/utils/dateTransform/constructFrom.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/utils/dateTransform/constructFrom">;
}
declare module "@power-rent/widget/Widget/utils/dateTransform/format.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/utils/dateTransform/format">;
}
declare module "@power-rent/widget/Widget/utils/dateTransform/getDay.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/utils/dateTransform/getDay">;
}
declare module "@power-rent/widget/Widget/utils/dateTransform/getHours.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/utils/dateTransform/getHours">;
}
declare module "@power-rent/widget/Widget/utils/dateTransform/getMinutes.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/utils/dateTransform/getMinutes">;
}
declare module "@power-rent/widget/Widget/utils/dateTransform/getWeek.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/utils/dateTransform/getWeek">;
}
declare module "@power-rent/widget/Widget/utils/dateTransform/getWeekYear.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/utils/dateTransform/getWeekYear">;
}
declare module "@power-rent/widget/Widget/utils/dateTransform/index" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/utils/dateTransform">;
}
declare module "@power-rent/widget/Widget/utils/dateTransform/index.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/utils/dateTransform">;
}
declare module "@power-rent/widget/Widget/utils/dateTransform/isDate.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/utils/dateTransform/isDate">;
}
declare module "@power-rent/widget/Widget/utils/dateTransform/isValid.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/utils/dateTransform/isValid">;
}
declare module "@power-rent/widget/Widget/utils/dateTransform/lib/formatters.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/utils/dateTransform/lib/formatters">;
}
declare module "@power-rent/widget/Widget/utils/dateTransform/setHours.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/utils/dateTransform/setHours">;
}
declare module "@power-rent/widget/Widget/utils/dateTransform/setMinutes.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/utils/dateTransform/setMinutes">;
}
declare module "@power-rent/widget/Widget/utils/dateTransform/startOfWeek.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/utils/dateTransform/startOfWeek">;
}
declare module "@power-rent/widget/Widget/utils/dateTransform/startOfWeekYear.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/utils/dateTransform/startOfWeekYear">;
}
declare module "@power-rent/widget/Widget/utils/dateTransform/toDate.js" {
  declare module.exports: $Exports<"@power-rent/widget/Widget/utils/dateTransform/toDate">;
}
