// flow-typed signature: 6c2afbbe489205f474d3465fc3704b39
// flow-typed version: <<STUB>>/@date-io/luxon_v1.3.11/flow_v0.110.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@date-io/luxon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@date-io/luxon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@date-io/luxon/build/index.esm' {
  declare module.exports: any;
}

declare module '@date-io/luxon/build' {
  declare module.exports: any;
}

declare module '@date-io/luxon/rollup.config' {
  declare module.exports: any;
}

declare module '@date-io/luxon/type' {
  declare module.exports: any;
}

// Filename aliases
declare module '@date-io/luxon/build/index.esm.js' {
  declare module.exports: $Exports<'@date-io/luxon/build/index.esm'>;
}
declare module '@date-io/luxon/build/index' {
  declare module.exports: $Exports<'@date-io/luxon/build'>;
}
declare module '@date-io/luxon/build/index.js' {
  declare module.exports: $Exports<'@date-io/luxon/build'>;
}
declare module '@date-io/luxon/rollup.config.js' {
  declare module.exports: $Exports<'@date-io/luxon/rollup.config'>;
}
declare module '@date-io/luxon/type/index' {
  declare module.exports: $Exports<'@date-io/luxon/type'>;
}
declare module '@date-io/luxon/type/index.js' {
  declare module.exports: $Exports<'@date-io/luxon/type'>;
}
