// flow-typed signature: 38211cd39f157a43ab9050d20ac64014
// flow-typed version: <<STUB>>/@dnd-kit/core_v6.0.8/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dnd-kit/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dnd-kit/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@dnd-kit/core/dist/core.cjs.development' {
  declare module.exports: any;
}

declare module '@dnd-kit/core/dist/core.cjs.production.min' {
  declare module.exports: any;
}

declare module '@dnd-kit/core/dist/core.esm' {
  declare module.exports: any;
}

declare module '@dnd-kit/core/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@dnd-kit/core/dist/core.cjs.development.js' {
  declare module.exports: $Exports<'@dnd-kit/core/dist/core.cjs.development'>;
}
declare module '@dnd-kit/core/dist/core.cjs.production.min.js' {
  declare module.exports: $Exports<'@dnd-kit/core/dist/core.cjs.production.min'>;
}
declare module '@dnd-kit/core/dist/core.esm.js' {
  declare module.exports: $Exports<'@dnd-kit/core/dist/core.esm'>;
}
declare module '@dnd-kit/core/dist/index' {
  declare module.exports: $Exports<'@dnd-kit/core/dist'>;
}
declare module '@dnd-kit/core/dist/index.js' {
  declare module.exports: $Exports<'@dnd-kit/core/dist'>;
}
