// flow-typed signature: c5502e7a50c9a30e9ed3b307f9176eae
// flow-typed version: <<STUB>>/@dnd-kit/sortable_v7.0.2/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dnd-kit/sortable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dnd-kit/sortable' {
  declare module.exports: any;
}
