// flow-typed signature: 2aa1b54fb67078b25e786d0e36c1188b
// flow-typed version: <<STUB>>/@dnd-kit/utilities_v3.2.1/flow_v0.142.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@dnd-kit/utilities'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@dnd-kit/utilities' {
  declare module.exports: any;
}
