// flow-typed signature: 9237aebaf544a5a38684b32723dc35bf
// flow-typed version: <<STUB>>/@graphql-tools/schema_v6.0.0/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@graphql-tools/schema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@graphql-tools/schema' {
  declare module.exports: any;
}
